version: '3'

services:
  ampachetest:
    build:
      context: .
      dockerfile: docker/Dockerfilephp82
    restart: on-failure
    ports:
      - "8989:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./ampache:/var/www/html
      - ./docker/log:/var/log/ampache
      - ./docker/media:/media
      - ./docker/data/sql:/tmp/sql
